"""empty message

Revision ID: 478ca31f15f3
Revises: 8a7149acecb7
Create Date: 2020-03-24 05:59:20.669470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478ca31f15f3'
down_revision = '8a7149acecb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'group',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'group',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###
