"""empty message

Revision ID: 8a7149acecb7
Revises: f92262f4bf8f
Create Date: 2020-03-23 13:23:50.328381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7149acecb7'
down_revision = 'f92262f4bf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deed', sa.Column('guests', sa.Integer(), nullable=True))
    op.add_column('deed', sa.Column('time_req', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deed', 'time_req')
    op.drop_column('deed', 'guests')
    # ### end Alembic commands ###
